### ISSUE TITLE
Texts overlapped on mermaid GANNT diagram

### ISSUE THREAD

**Issue by czhiling** [typora/typora-issues#1053]
I was tring following mermaid code to draw GANNT diagram on typora.
```mermaid
gantt
dateFormat  YYYY-MM-DD
title Adding GANTT diagram to mermaid

section A section
Completed task            :done,    des1, 2014-01-06,2014-01-08
Active task               :active,  des2, 2014-01-09, 3d
Future task               :         des3, after des2, 5d
Future task2               :         des4, after des3, 5d
```
I got the image:
![default](https://user-images.githubusercontent.com/218637/32851989-3be5208c-c9fc-11e7-957b-6a5a9babdfce.jpg)

"A section" is overlapped on active task, which looks not good. Is it possible to solve this?

Thanks!

Zhiling

**Comment by abnerlee** [comment]
should be fixed already

**Comment by czhiling** [comment]
Yes, It's fixed. Thanks a lot!

**Comment by cnshijin** [comment]
@czhiling how to fixed it? I have the the same problem on the newest release. Thank you!

**Comment by czhiling** [comment]
@abnerlee I still encounter the issue. 

In principle, It might be mitigated by using a smaller font. But I do not know how to do it. 

![untitled_3](https://user-images.githubusercontent.com/218637/39803490-befb2256-53a3-11e8-8867-94a039c83dd1.jpg)

**Comment by abnerlee** [comment]
put to https://github.com/knsv/mermaid/issues/661

**Comment by cnshijin** [comment]
It's not exactly because of a long section name. It's different with the same gantt mermaid between typera and live editor. @abnerlee 
![live editor](https://user-images.githubusercontent.com/22090374/39902725-29252d8e-5502-11e8-9ac1-312dc2bee5c6.png)
![typora](https://user-images.githubusercontent.com/22090374/39902726-2979a08a-5502-11e8-80b6-c13002eb6a16.png)
