### ISSUE TITLE
Auto refresh not working anymore

### ISSUE THREAD

**Issue by ghost** [typora/typora-issues#2600]
Auto refresh was working with version 0.9.70 (windows build).
After updating to 0.9.72, auto refresh seems to have reverted. 

With autosave preference enabled. I tried the following steps:
1. Open a markdown file in Typora. (No pending changes in Typora)
2. Open the same file in another editor (Notepad++). Modify and save.
3. Switch focus to Typora. Observed that the change did not appear in Typora.
4. Switch focus back to other editor. Observed that Typora autosave reverted the changes.

With autosave preference disabled. I tried the following steps:
1. Open a markdown file in Typora. (No pending changes in Typora)
2. Open the same file in another editor (Notepad++). Modify and save.
3. Switch focus to Typora. Observed that the change did not appear in Typora. (Typora knows the file contains changes, see black spot beside filename in title)
4. Click File -> Reopen with encoding -> Auto. Typora loads file with changes.

Expected behaviour:
1. Open a markdown file in Typora. (No pending changes in Typora)
2. Open the same file in another editor (Notepad++). Modify and save.
3. Switch focus to Typora.  Typora auto refresh the file and shows the changes made in the other editor.

**Comment by abnerlee** [comment]
should be fixed

**Comment by Jexraiden** [comment]
Typora still has this problem. I have some files in Google Drive and sync with my PC. Even though the files are synced and I can open in other markdown apps, in Typora it doesn't update the file. It is still showing the old version of the file. Please reopen this issue.

Typora version 0.9.8.1

Typora is still not reliable, I almost lost my work done because I almost saved the file. If I had configure to autosave I would be screwed. This is a serious issue.

**Comment by wirerydr** [comment]
This continues not to work, and is more than simply annoying - it is a deal-breaker for me to continue using Typora.  

While this is (hopefully) being looked at for resolution, There a workaround, however it is manually triggered:  The **`File -> Reopen with Encoding -> Auto`** feature.

Sadly this has no keyboard shortcut by-default (and it really should, at-least until the auto-refresh issue is fixed).  However one can add it themselves, following the process documented at https://support.typora.io/Shortcut-Keys/ .  Note that on Windows, you'll have to manually edit a .JSON file.  Also note that as per issue #987, the correct label to use for this specific shortcut is "Auto", so you'll end up with a stanza looking something like the following:
```json
  // Custom key binding, which will override the default ones.
  "keyBinding": {
    // for example: 
    // "Always on Top": "Ctrl+Shift+P"
    "Auto": "Ctrl+Shift+P",
  },
```
You can, of-course, choose whatever actual key-combination works best for you.

Having said all this, I will agree with commenters in this and other related issues, that this is a crucial behaviour that makes-or-breaks my ability to use Typora.

**Comment by abnerlee** [comment]
@wirerydr Possible to provide more details, like the files are edited by which app?

**Comment by wirerydr** [comment]
> @wirerydr Possible to provide more details, like the files are edited by which app?

My Windows 10 workstation has several SMB-based network shares mounted, that are remotely provided by a FreeNAS server.  So I have been able to test auto-refresh on with files on both local filesystems and SMB-shared filesystems.  So my environment consists of the following:

Local Workstation: **Windows 10 v2004 (build 19041.207)**
Remote Fileserver: **FreeNAS-11.3-U2**
Remote Samba: **4.10.13**
Typora: **0.9.83 (beta)**
Local GVim: **8.2**



I have tested the following on my Windows 10 workstation:

| File Location | Local Editor | Test Result |
| -------- | -------- | ----- |
| X: (SMB share) | gvim | Typora failed to auto-refresh |
| X: (SMB share) | notepad.exe | Typora failed to auto-refresh |
| C: (local filesystem) | gvim | Typora failed to auto-refresh |
| C: (local filesystem) | notepad.exe | Typora failed to auto-refresh |

In each case, if I saved changes to the file in my local editor, and then switched focus back to Typora, there was no observable auto-refresh.  If I then triggered Typora's **_File -> Reopen with Encoding -> Auto_** feature, then the changes got updated within Typora.

Let me know if there are any additional details that would assist you.

**Comment by abnerlee** [comment]
would you try 0.9.86?

**Comment by wirerydr** [comment]
> 
> 
> would you try 0.9.86?

Tested 0.9.86, and the new version does indeed appear to be doing auto-refresh properly.  Tested with files on both local and samba-mounted filesystems.  When changes are written to the file, then almost immediately Typora updates its display to reflect the changes.

Strangely, sometimes a popup appears first saying something like _**file contents have changed - do you want to reload?**_.  Other times, there is no popup and Typora just refreshes immediately.

I will continue testing, but it looks like this can be closed.

**Comment by karimmd** [comment]
The auto refresh does not work in Typora 0.9.95 on Linux. I am using the Keyboard shortcut Ctrl+Shift+P to do it manually.

**Comment by Yaojian** [comment]
0.10.9 still contains this bug

**Comment by noperator** [comment]
I'm still experiencing this issue, too. Some details for context:

- OS: Linux (see also: #3841)
- Distro: Debian 10 (buster)
- Typora version: 0.10.11 (beta)
- Installation method: [Typora's APT repository](https://typora.io/#linux), vanilla/default configuration

I recorded a demo of this problem following [this example](https://github.com/typora/typora-issues/issues/894#issue-255989264) in a related issue. Typora fails to auto-refresh when the file's contents are updated, either when simply appending to the file or editing it interactively in Vim.

![typora-demo](https://user-images.githubusercontent.com/6006772/124686368-00d51e80-dea1-11eb-998f-c6a2251e46f2.gif)

> This is a deal-breaker for me to continue using Typora.

I hate to agree—but I've been seeking other Linux-based Markdown editors due to Typora's refusal to auto-refresh. I don't like any of the alternatives, though :slightly_smiling_face: Please let me know if I can provide any more information as I'd love to see this resolved.

**Comment by kevinkleine** [comment]
Same issue

OS: Linux
Distro: Manjaro / Gnome 40.2
Typora version: 0.10.11 (beta)
Installation method: AUR

**Comment by abnerlee** [comment]
try 0.11.2?

**Comment by noperator** [comment]
Just tried v0.11.2, and auto-refresh still rarely works. The demo I shared above is still representative of my experience after the upgrade.

**Comment by cgosorio** [comment]
The problem persists in Typora 0.11.5 (beta) for Linux (Linux Mint 20.2 Uma). For now, I am handling it using the [shortcut trick](https://github.com/typora/typora-issues/issues/2600#issuecomment-614452004) proposed by @wirerydr, but it's really annoying not having the automatic refresh.

**Comment by noperator** [comment]
Interestingly, when I move my Markdown file to `/tmp`, auto-refresh works _very_ consistently. Haven't seen it fail yet—I'll update this comment if that happens.

**Comment by sdbbs** [comment]
Just to note - I just updated to Typora 0.11.13 on Windows 10, and as I'm not using Typora often, so I just landed on this page looking for a way to auto-refresh. So, I just noticed, that I do not have File/Reopen with encoding menu entry... Has it been removed?

**Comment by noperator** [comment]
As of v1.0.3, auto-refresh seems to work as expected again for me.

**Comment by leowill01** [comment]
I'm still experiencing this issue on macOS. It hasn't worked for as long as I can remember. If the same file is open in Typora, VS Code, RStudio, and Obsidian, a change in any will be automatically refreshed in the other three, while a change in any of the other 3 will not be automatically refreshed in Typora. In order to reflect changes in Typora, I have to ***absolutely make sure*** that I press `Revert` after pressing `Save` in Typora to make it reflect external changes. This makes me unable to rely on fidelity of the document being shown in Typora.

**Comment by anirudh-eka** [comment]
I'm facing this issue too:
- macOS 11.3.1
- Typora 1.0.5

If this issue fixed, I'd highly recommend Typora

**Comment by mattiasJohnson** [comment]
I'm facing this issue too, the first edit I make to a file in another program gets instantly shown in Typora but the following edits do not appear automatically. 

The solution of with above [Reopen with Encoding](https://github.com/typora/typora-issues/issues/2600#issuecomment-614452004) does not completely work for me either: When I edit a file outside of Typora and then press `Reopen with Encoding>Auto`  it only works once, if I repeat the process the following changes are not shown. But if I then do `Reopen with Encoding>UTF-8` it works but also this strategy only the first time. The clumsy workaround is to every other time reopen with Auto and every other time reopen with UTF-8. In my workflow I've now got a script (in autokey) on Winkey+R that presses both the key combinations for reopening with Auto and reopening with UTF-8 so that it always works.

I'm running:
Ubuntu 20.04
Typora 1.2.4

**Comment by CalamariDude** [comment]
any update on this? I face this issue on 1.2.4 on both mac (catalina) and ubuntu 22.04

**Comment by abnerlee** [comment]
For 1.2.4, could you provide a sample operation that will cause auto refresh not working?

**Comment by jemshid** [comment]
> This continues not to work, and is more than simply annoying - it is a deal-breaker for me to continue using Typora.
> 
> While this is (hopefully) being looked at for resolution, There a workaround, however it is manually triggered: The **`File -> Reopen with Encoding -> Auto`** feature.
> 
> Sadly this has no keyboard shortcut by-default (and it really should, at-least until the auto-refresh issue is fixed). However one can add it themselves, following the process documented at https://support.typora.io/Shortcut-Keys/ . Note that on Windows, you'll have to manually edit a .JSON file. Also note that as per issue [#987](https://github.com/typora/typora-issues/issues/987), the correct label to use for this specific shortcut is "Auto", so you'll end up with a stanza looking something like the following:
> 
>   // Custom key binding, which will override the default ones.
>   "keyBinding": {
>     // for example: 
>     // "Always on Top": "Ctrl+Shift+P"
>     "Auto": "Ctrl+Shift+P",
>   },
> You can, of-course, choose whatever actual key-combination works best for you.
> 
> Having said all this, I will agree with commenters in this and other related issues, that this is a crucial behaviour that makes-or-breaks my ability to use Typora.

This didn't work for me on 1.12.4 on Ubuntu Linux 24.04

**Comment by cumanzor** [comment]
Still an issue on macOS 26.3 (Typora 1.12.6)

**Comment by r1pvanw1nkl3** [comment]
This doesn't work at all for me either. MacOS 26.3.1 and Typora 1.13.4.

I'm frequently using Typora to read/edit markdown files alongside an agent. There is no auto-reload, pop-up, etc. that happens. Also tried editing a file manually using Obsidian, and no auto-reload.

This is a buy or not buy issue for me - nearing the end of my evaluation period.

**Comment by Joc007** [comment]
I'm on 1.13.4 (7690) on macOS and this one thing keeps annoying me.
Paid user.

**Comment by TheNetworker** [comment]
still not working as of now - auto-reload or refresh not working
