### ISSUE TITLE
image load failed

### ISSUE THREAD

**Issue by Konfido** [typora/typora-issues#2780]
![load_pic](https://user-images.githubusercontent.com/25447610/64008378-976b8280-cb48-11e9-858f-5c9970ef072e.gif)

Description (Version: 0.9.9.28 (3403), Mac) :  
- images will load and show in current file, but it fails irregularly when you open an existing file.
- The pic will load somehow when you revise it. 
- Occasionally this issue may disappear when I reopen Typora
- YAML:
```
title: xxx
categories: [xx]
tags: [xx]
typora-root-url: ..
typora-copy-images-to: ../images
date: 2018-08-24 17:42:13
```
- file layout
```
.
├── images
│   └── EpM4ZVXBKNJnGm.png
└── Research
    └── xxx-xxx.md
```

**Comment by abnerlee** [comment]
Is there any steps to reproduce this bug?

**Comment by silvermagic** [comment]
I had the same problem on Mac. The picture of the article cannot be displayed after reopening the article, but as long as the Markdown statement of the picture is edited, for example, enter a carriage return at the front, the picture can be displayed normally. 
It seems that this situation does not exist when using english as the path name. After my test, it may be related to the path name. I'm from China, using unicode characters.

**Comment by silvermagic** [comment]
I had the same problem on Mac. The picture of the article cannot be displayed after reopening the article, but as long as the Markdown statement of the picture is edited, for example, enter a carriage return at the front, the picture can be displayed normally.
It seems that this situation does not exist when using english as the path name. After my test, it may be related to the path name. I'm from China, using unicode characters.

**Comment by silvermagic** [comment]
I had the same problem on Mac. 

$ tree .
.
├── A
│   ├── aa.assets
│   │   └── 1-7-20200110162854984.png
│   ├── aa.md
│   └── bb.md
├── a.assets
│   └── 1-7-20200110162844832.png
├── a.md
└── b.md

3 directories, 6 files

file access sequence:

- a.md -> b.md -> a.md : Picture(a.md) shows normal
- a.md -> bb.md -> a.md : Pictures(a.md) are not displayed properly
- aa.md -> bb.md -> aa.md : Picture(aa.md) shows normal
- aa.md -> b.md -> aa.md : Pictures(aa.md) are not displayed properly

- a.md -> bb.md -> a.md -> b.md -> a.md : Picture(a.md) shows normal
- aa.md -> b.md -> aa.md -> bb.md -> aa.md : Picture(a.md) shows normal

From the experimental results, the other files in the same directory must be accessed first and then the files with pictures can be displayed normally.

**Comment by abnerlee** [comment]
should be fixed in new release

**Comment by junxy** [comment]
Any updates?

The `version:0.9.86(beta)` I use still has this problem, and oddly enough `VS Code` also has this problem.

Other pictures will display normally. Only one of the pictures was in trouble. Tried it, renamed the image, converted the image format, still not working.

**Comment by abnerlee** [comment]
@junxy We believe it is fixed already. If you have the issue, could you provide more details for reproduce?

**Comment by onlinelei** [comment]
I have the same problem as @junxy , `version:0.9.89(beta)`  Windows 10 

only one picture load failed, but can open in the browser

picture url is https://gitee.com/suqianlei/Pic-Go-Repository/raw/master/img/20200619181535.png

**Comment by viggy28** [comment]
On mac Version 0.9.9.35.2 (4715), getting "image load failed" for https://github.com/viggy28/til/blob/master/federico-tasin-88iv9rYyEeE-unsplash.jpg

On the other hand, I am able to display the image used in https://support.typora.io/Images/. Attaching screenshot.
<img width="929" alt="Screen Shot 2020-09-17 at 7 20 23 PM" src="https://user-images.githubusercontent.com/15543619/93547982-1c276b00-f91b-11ea-820a-94ef1c57dc82.png">


Am I missing anything?

**Comment by abnerlee** [comment]
https://github.com/viggy28/til/blob/master/federico-tasin-88iv9rYyEeE-unsplash.jpg return a html page, not a png file

**Comment by whitecoffee** [comment]
It still happens -- version 0.9.98(beta), windows x64
Should I provide the files?

**Comment by YiffyToys** [comment]
Still happens 0.10.1 Windows 64 bit with local png files and relative as well as absolute pathes (network drive).

**Comment by douglasware** [comment]
Does not work under any circumstances for me in Windows 0.10.1 (beta)

**Comment by YiffyToys** [comment]
Same here in 0.10.1 beta but the last stable version (not to be found on the download-page but very well hidden in the changelog) works.

**Comment by abnerlee** [comment]
fixed, please check update

**Comment by douglasware** [comment]
Works for me in 0.13! Thanks

**Comment by zhaoqingqing** [comment]
this problem resolve in new version?

**Comment by valexandersaulys** [comment]
Works for me if I use a correct filename suffix. Typora does not check for file type at insertion, only bases it on file suffix (I think?)

**Comment by ste1** [comment]
still have the problem in the latest version. I installed it without admin rights on Windows.

**Comment by HillCat** [comment]
When Upgrade to the newest release , My local host images can not display, I used relative path.
![image](https://user-images.githubusercontent.com/41800196/155871908-1d7d92fe-12a2-4faf-8abb-aee52dc107cc.png)

**Comment by matt99991** [comment]
I'm seeing this same issue on Typora 1.2.4 on macOS 12.3.1.

**Comment by abnerlee** [comment]
@HillCat  could you try v1.2.5

**Comment by niyaodong** [comment]
Win 10上，1.4.8也有一样的问题。
