### ISSUE TITLE
Windows Version newest, always scroll to top when add headings.

### ISSUE THREAD

**Issue by leewi9** [typora/typora-issues#301]
after adding headings and press `Ctrl+s` to save, Typora always scroll to top.

**Comment by abnerlee** [comment]
@leewi9 Please upgrade to newest version, and see if it still happens or not.

If still happens, could you provide detailed steps to reproduce this

**Comment by leewi9** [comment]
@abnerlee Thanks, the unnecessary scroll has been fixed. However, my custome css couldn't be in effect after upgrade. (I do copy the my backup css and paste in the new version's `style` folder.)

**Comment by abnerlee** [comment]
@leewi9 do you write a css file? If so, what's its filename? Uppercase and whitespace is not supported, you should name it like `my-css-theme.css`

**Comment by leewi9** [comment]
I modify the css file directly in the `github.css` file. Pls see below screenshot.

![image](https://cloud.githubusercontent.com/assets/10832544/18827148/e0d4c470-8403-11e6-8963-4b0caa3d3789.png)

**Comment by abnerlee** [comment]
@leewi9, please check the following:

1. Please put the css file under "typora's theme folder", which can be opened from preference panel, but not in "Program Files".
2. If still not work, please debug in Typora, and see whether the css rule is overwritten by more strict css selectors.

Some reference:

http://support.typora.io/Add-Custom-CSS/
http://theme.typora.io/doc/Install-Theme/
http://theme.typora.io/doc/Write-Custom-Theme/
