### ISSUE TITLE
typora incorrectly handles codeblocks in the ordered list

### ISSUE THREAD

**Issue by ViliusS** [typora/typora-issues#4185]
Typora incorrectly handles codeblocks in the ordered list. According to basic Markdown specification such codeblocks should be indented 8 spaces or 2 tabs. If text in ordered list is indented 4 spaces it should be treated as a text part of the list, not the codeblock.

See the example below.

```
1. first item
2. second item
3. third item part1:

<8spaces>my code
<8spaces>run something

<4space>third item part2:

<8spaces>another code
<8spaces>do something more

4. fourth item
```

#### It should produce:
1. first item
2. second item
3. third item part1:

        my code
        run something

    third item part2:

        another code
        do something more

4. fourth item

#### However Typora displays something like:
1. first item
2. second item
3. third item part1:

```
    my code
    run something

third item part2:
```
```
    another code
    do something more
```

4. fourth item

**Comment by abnerlee** [comment]
I'm not able to reproduce this in 0.9.9.36.2

Does this still exists for latest version?

**Comment by ViliusS** [comment]
Yes, this is on newest 0.9.98 on Windows. See this file as an example: https://github.com/VFPX/Thor/blob/master/Docs/Thor_install.md

![image](https://user-images.githubusercontent.com/2323565/108621753-3969e380-743d-11eb-8c1c-5a8ac7fa7748.png)

**Comment by abnerlee** [comment]
relates #2269

**Comment by abnerlee** [comment]
fixed in new release

**Comment by ViliusS** [comment]
Not fixed at least to me on latest 0.10.6.

**Comment by abnerlee** [comment]
@ViliusS could you provide new sample md file?

**Comment by ViliusS** [comment]
The same MD sample still doesn't work https://github.com/VFPX/Thor/blob/master/Docs/Thor_install.md

--
   Vilius

________________________________________
Nuo: AbnerLee ***@***.***>
Išsiųsta: 2021 m. balandžio 28 d., trečiadienis 14:41
Iki: typora/typora-issues
Kopija: Vilius Šumskas; Mention
Tema: Re: [typora/typora-issues] typora incorrectly handles codeblocks in the ordered list (#4185)

@ViliusS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FViliusS&data=04%7C01%7C%7C86c9459cab18453ce52108d90a3a85c4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637552068727100016%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hlHmnJk9EcvXJSS8KLDVMP5%2Fek6zdS6PB7sQ6Kstqhc%3D&reserved=0> could you provide new sample md file?
