### ISSUE TITLE
Typora export pdf file, the last page is empty page

### ISSUE THREAD

**Issue by saup007** [typora/typora-issues#770]
Typora export pdf file, the last page is empty page #770

**Comment by lloyd094** [comment]
Can confirm, though I only seem to notice it when the last page is fairly full (like almost a "whole" page).

**Comment by abnerlee** [comment]
Fixed in v0.9.9.10

**Comment by neclipse** [comment]
The issue is still here in version 0.10.11

**Comment by abnerlee** [comment]
> The issue is still here in version 0.10.11

Could you provide a sample md file?

**Comment by neclipse** [comment]
Hi AbnerLee,

 

Please see attached .md file and the exported pdf file as well. You can find the blank page in the .pdf. My typoya version on my windows desktop is 0.10.11.

 

Best regards,

 

Chang

**Comment by DevaWu** [comment]
The pb still occured on version 0.11.6 (beta), maybe couse of I didn't use the default margins.

**Comment by deciacco** [comment]
Still happening in 1.0.3. If the last page is mostly full, PDF export will create a blank, last page.

**Comment by LAWTED** [comment]
still in v1.2

**Comment by abnerlee** [comment]
fixed in v1.3.6
